// frontend-react/src/components/auction-card.tsx
import { Auction } from "@/models/Auction";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "./ui/card";
import { Link } from "@tanstack/react-router";

export default function AuctionCard(auctionProps: Auction) {
  return (
    <>
      <Link to={`/auction/${auctionProps.Auction_Id}`}>
        <Card className="p-1 transition-colors hover:bg-accent hover:text-accent-foreground">
          <CardHeader className="mb-[-16px]">
            <CardTitle>{auctionProps.Title}</CardTitle>
            <CardDescription>
              Created: {auctionProps.Created_At}
            </CardDescription>
          </CardHeader>
          <CardContent>
            <p className="mb-2">{auctionProps.Description}</p>
            {auctionProps.Number_Of_Bids === 0 ? (
              <p>Starting Price: {auctionProps.Current_Price} NOK</p>
            ) : (
              <p>Current Price: {auctionProps.Current_Price} NOK</p>
            )}
            <p className="ml-4">
              <i>{auctionProps.Number_Of_Bids} bids</i>
            </p>
          </CardContent>
        </Card>
      </Link>
    </>
  );
}

// frontend/src/components/auction/AuctionCard.vue
<template>
  <v-card>
    <v-card-title>{{ props.auction.Title }}</v-card-title>
    <v-card-subtitle
      >Number of Bids: {{ props.auction.Number_Of_Bids }}</v-card-subtitle
    >
    <v-card-subtitle
      >Created at: {{ props.auction.Created_At }}</v-card-subtitle
    >
    <v-card-text
      >Starting Price: {{ props.auction.Starting_Price }}</v-card-text
    >
    <v-card-text>Current Price: {{ props.auction.Current_Price }}</v-card-text>
    <v-card-text>Description: {{ props.auction.Description }}</v-card-text>
    <v-card-text>Winner: {{ props.auction.Winner }}</v-card-text>
    <v-card-actions>
      <v-btn
        variant="outlined"
        @click="navigateToAuction(props.auction.Auction_Id)"
      >
        Go to Auction: {{ props.auction.Title }}
      </v-btn>
    </v-card-actions>
  </v-card>
</template>

<script setup lang="ts">
import { defineProps } from "vue";
import router from "@/router";

const props = defineProps<{ auction: any }>();

const navigateToAuction = (auctionId: string) => {
  router.push(`/auction/${auctionId}`);
};
</script>
